customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('', views.index, name='index'),
    path('check/', views.checkCustomer, name='check'),
    path('forgotPassword', views.forgotPassword, name='forgotPassword'),
    path('userInfo', views.userInfo, name='userInfo'),
    path('listCoach', views.listCoach, name='listCoach'),
    path('datve', views.datve, name='datve'),
    path('_login', views.loginView, name='login'),
    path('quanlyve', views.quanlyveView, name='login'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customers.urls')),
    path('manager', include('managers.urls')),
]

customers/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    fullName = models.CharField(max_length=50)
    phoneNumber = models.CharField(max_length=15)
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=200)

    def __unicode__(self):
        return self.content
    

customers/forms.py
from django import forms
from .models import Customer

class CreateCustomersForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('fullName', 'email', 'password', 'phoneNumber')

class SigninCustomersForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('email', 'password',)

customers/views.py
from django.http import HttpResponse
from .models import Customer
from managers.models import Ticket,Trip,Seat,Garage
from django.urls import reverse
from django.db import transaction,IntegrityError
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
import random 
import string
from datetime import datetime
# import phonenumbers
# Create your views here.
number_chair1=""
number_chair2=""
number_chair3=""
def index(request):
   return render(request, 'customers/index.html')

def loginView(request):
   return render(request, 'customers/login/login_view_notify.html')

def quanlyveView(request):
   content = quanlyveInfo(request)
   return render(request, 'customers/user_info/quanlyveView.html',content)

def userInfo(request):
   content = {}
   if 'fullname' in request.session:
        if (request.session['fullname']):
            fullname = request.session['fullname']
            content['fullname'] = fullname
   if 'email' in request.session:
        if (request.session['email']):
            email = request.session['email']
            content['email'] = email
   if 'numberPhone' in request.session:
        if (request.session['numberPhone']):
            numberPhone = request.session['numberPhone']
            content['numberPhone'] = numberPhone
   return render(request, 'customers/user_info/userInfo.html',content)

@csrf_exempt
def checkCustomer(request):
    if request.method == 'POST':
            login_data = request.POST.dict()
            numberPhone = login_data['numberPhone']
            password = login_data['password']
            num_rows = Customer.objects.filter(phoneNumber=numberPhone, password=password).count()
            nameUser=""
            emailUser = ""
            sql = "SELECT * FROM customers_customer where phoneNumber =" + numberPhone
            User = Customer.objects.raw(sql)
            for data in User:
                nameUser=data.fullName
                emailUser=data.email
            if num_rows > 0:
                request.session['numberPhone'] = numberPhone
                request.session['fullname'] = nameUser
                request.session['email'] = emailUser
                messages = "Đăng nhập thành công!"
                getTripByTicket(request,numberPhone)
                content = {'numberPhone': numberPhone, 'messages': messages}
                return redirect(reverse('customers:userInfo', kwargs = {}))
            else:
                messages = "Số điện thoại hoặc mật khẩu không đúng!"
                content = {'messages': messages}
                return render(request, 'customers/login/login_view.html',content)
    return HttpResponse("Sai method")

@csrf_exempt
def forgotPassword(request):
    if request.method == 'POST':
        login_data = request.POST.dict()
        numberPhone = login_data['numberPhoneForgotPassword']
        num_rows = Customer.objects.filter(phoneNumber=numberPhone).count()
        if num_rows > 0:
            _password = _pw(8)
            updatePassword = "UPDATE customers_customer  SET password = "+ _password  + "WHERE phoneNumber = " + numberPhone
            Customer.objects.raw(updatePassword)
            sql = "SELECT * FROM customers_customer where phoneNumber =" + numberPhone
            User = Customer.objects.raw(sql)
            for data in User:
                nameUser=data.fullName
                emailUser=data.email
                passwordNew = data.password
            messages = "Đã đổi mật khẩu thành công!"
            content = {'numberPhone': numberPhone, 'messages': messages}
            data = "Xin chào: " + nameUser+ " chúng tôi vừa cập nhật lại mật khẩu cho bạn, mật khẩu mới là: " + passwordNew
            send_mail('Welcome!', data, "PLC", [emailUser], fail_silently=False)
            return render(request, 'customers/success.html')
        else:
            messages = "Số điện thoại không đúng!"
            content = {'messages': messages}
            return render(request, 'customers/login/login_view_notify.html',content)
    return HttpResponse("Sai method")
    

# def listCoach(request):
#     return render(request, 'customers/listCoach.html')

@csrf_exempt
def datve(request):
  if request.method == 'POST':
    data = request.POST.dict()
    idChuyen = request.POST.get('inputIdChuyenXe', '')
    idGhe1 = request.POST.get('seatID1', '')
    idGhe2 = request.POST.get('seatID2', '')
    idGhe3 = request.POST.get('seatID3', '')
    diemDon = request.POST.get('checkbox', '')
    diemTra = request.POST.get('_checkbox', '')
    tenKh = data['nameUser'+ str(1)]
    phoneUser = data['phoneUser'+ str(1)]
    email = data['emailUser'+ str(1)]
    password = _pw(8)
    sid = transaction.savepoint()
    # add Customer
    if idChuyen != "" and diemDon != "" and diemTra != "":
        kh =  Customer()
        kh.fullName = tenKh
        kh.phoneNumber = phoneUser
        kh.email = email
        kh.password = password
        kh.save()

    # add Ticket
        sqlDiemDon = "SELECT id,musty from managers_schedule where id = " + str(diemDon)
        _Schedule = Schedule.objects.raw(sqlDiemDon)
        for data in _Schedule:
            mustyDon=data.musty

        sqlDiemTra = "SELECT id,musty from managers_schedule where id = " + str(diemTra)
        _Schedule = Schedule.objects.raw(sqlDiemTra)
        for data in _Schedule:
            mustyTra=data.musty

        sql = "SELECT id from customers_customer where phoneNumber = " + str(phoneUser)
        User = Customer.objects.raw(sql)
        for data in User:
            idUser=data.id
        
        _idChuyen = idChuyen
        _idSeat1 = idGhe1
        _idSeat2 = idGhe2
        _idSeat3 = idGhe3
        _idCustomer= idUser
        _diemDon= diemDon

        if(_idSeat1 != "" and _idChuyen != "" and _diemDon != "" and _idCustomer != ""):
          
            if _idSeat1 != "" :
                ticket = Ticket()
                ticket.trip_id = _idChuyen
                ticket.seat_id = _idSeat1
                ticket.customer_id = _idCustomer
                ticket.schedule_id = _diemDon
                ticket.save() 

                seat = "SELECT * FROM managers_seat WHERE id = " + str(idGhe1)
                _Seat = Seat.objects.raw(seat)
                for data in _Seat:
                    number_chair1=data.number_chair
            if  _idSeat2 != "" :
                ticket = Ticket()
                ticket.trip_id = _idChuyen
                ticket.seat_id = _idSeat2
                ticket.customer_id = _idCustomer
                ticket.schedule_id = _diemDon
                ticket.save() 
                
                seat = "SELECT * FROM managers_seat WHERE id = " + str(idGhe2)
                _Seat = Seat.objects.raw(seat)
                for data in _Seat:
                    number_chair2=data.number_chair
            if _idSeat3 != "":
                ticket = Ticket()
                ticket.trip_id = _idChuyen
                ticket.seat_id = _idSeat3 
                ticket.customer_id = _idCustomer
                ticket.schedule_id = _diemDon
                ticket.save() 
                
                seat = "SELECT * FROM managers_seat WHERE id = " + str(idGhe3)
                _Seat = Seat.objects.raw(seat)
                for data in _Seat:
                    number_chair3=data.number_chair
           
            trip = "SELECT * from managers_trip where managers_trip.id =" + str(_idChuyen);
            _getTrip = Trip.objects.raw(trip)
            for data in _getTrip:
                departure= data.departure
                destination=data.destination
                departure_time=data.departure_time
                price=data.price

            data = "Xin chào bạn: Cảm ơn bạn đã đặt vé bên công ty chúng tôi, đây là thông tin vé của bạn :\nGhế số: " + number_chair1 + " " + number_chair2 +"" +  str(number_chair3) + " \nĐịa điểm đón: "  + str(mustyDon) + " " + destination +  " \nĐịa điểm trả: " + str(mustyTra) +" " +  departure + "\nGiờ khởi hành: " + str(departure_time) + "\nGiá vé: " + str(price)+".000" +"\nTài khoản để đăng nhập để kiểm tra vé là: Tên đăng nhập: " + phoneUser +" " + "Mật khẩu: "+ password;
            send_mail('Welcome!', data, "PLC", [email], fail_silently=False)
            print("done")
        if IntegrityError:
                transaction.savepoint_rollback(sid)
        else:
                try:
                    transaction.savepoint_commit(sid)
                except IntegrityError:
                    transaction.savepoint_rollback(sid)
        return render(request, 'customers/success.html')
  return HttpResponse("Sai method")

def _pw(length=8):
    s = ''
    for i in range(length):
        s += random.choice(string.digits)
    return s

def getTripByTicket(request,phoneNumber):
    idTrip = "SELECT 1 as id, managers_ticket.trip_id,managers_ticket.seat_id from managers_ticket join customers_customer on customers_customer.id = managers_ticket.customer_id where phoneNumber = " + phoneNumber;
    _Trip = Ticket.objects.raw(idTrip)
    # getTrip
    for data in _Trip:
        trip_id=data.trip_id
        seat_id=data.seat_id
        seat_id2 = data.seat_id
    trip = "SELECT * from managers_trip where managers_trip.id =" + str(trip_id);
    _getTrip = Trip.objects.raw(trip)
    for data in _getTrip:
        departure= data.departure
        destination=data.destination
        departure_time=data.departure_time
        price=data.price
        garage_id=data.garage_id
        # getGarage 
        idGarage = "SELECT * FROM managers_garage WHERE id = " + str(garage_id);
        _Garage = Garage.objects.raw(idGarage)
        for data in _Garage:
            fullnameGarage=data.fullName
            description=data.description
        # getSeat 
        seat1 = "SELECT * FROM managers_seat WHERE id = " + str(seat_id);
        _Seat1 = Seat.objects.raw(seat1)

customers/templates/customers/login/header_logined.html
{% load static %}
<!-- header -->
<header class="container-fluid myNavBar">
	<nav class="navbar navbar-expand-md navbar-light">
		<div class="col-md-8 col-xl-7 col-lg-9 col-sm-6 d-flex">
			<a class="navbar-brand" href="/">
				<img src="{% static 'customers/images/logo1.png' %}" alt="">
			</a>
			<div class="Categories">
			</div> 
			<div class="input-search">
				<form action="#">
					<div class="input-group">
						<input type="text" class="form-control"
							placeholder="Search for anything">
						<div class="input-group-prepend">
							<span class="input-group-text"> <i class="fa fa-search"></i>
							</span>
						</div>
					</div>
				</form>
			</div>

		</div>
		<div class="col-md-4 col-xl-5 col-lg-3 col-sm-4">

			<div class="collapse navbar-collapse" id="collapsibleNavId">

				<ul class="navbar-nav">
					<li class="nav-item business"><a class="nav-link"
						href="/quanlyve">
							<i class="fas mr-2 fa-bus-alt"> </i>Quản lý vé
					</a></li>
					<li class="nav-item teach"><a class="nav-link" href="#"></a></li>
					<li class="nav-item">
						<div class="drop">
							<div class="dropdown">
								<button class="dropdown__btn d-flex">
									<i class="fas fa-user"></i>
								</button>
								<div class="dropdown__list">
									<a
										href="{% url 'customers:userInfo' %}"
										class="dropdown__item"><i class="fas mr-2 fa-user-alt"></i></i>Thông
										tin tài khoản</a> <a href="/"
										class="dropdown__item"><i class="fas mr-2 fa-sign-out-alt"></i>Đăng
										xuất</a>
								</div>
							</div>
						</div>
					</li>

				</ul>
			</div>
		</div>


	</nav>
</header>

customers/templates/customers/login/login_view.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
<title>HomePage</title>

<meta charset="utf-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- font awesome -->
<link rel="stylesheet" href="{% static 'customers/css/index.css' %}">
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
	integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
	crossorigin="anonymous" referrerpolicy="no-referrer" />


<!-- Bootstrap CSS -->
<link rel="stylesheet"
	href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
	crossorigin="anonymous">

<script
	src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
	integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
	crossorigin="anonymous"></script>

<style>
.invalid {
	border-color: red !important;
}

#error {
	color: red
}

#error2 {
	color: red
}
</style>

</head>

<body>
  {% include 'customers/login/login_view_notify.html' %}
	<!-- Cover -->
	<section class="myCover">
		<div class="cover__content">
			<div class="row tool-search">
				<div class="drop col-3">
					<div class="dropdown">
						<input placeholder="Nhập nơi đi ..." class="form-control"></input>
						<div class="dropdown__list">
							<a href="#" class="dropdown__item">Hà Nội</a> <a href="#"
								class="dropdown__item">Quảng Ning</a> <a href="#"
								class="dropdown__item">Sài Gòn</a> <a href="#"
								class="dropdown__item">Đà Nẵng></a>
						</div>


					</div>
				</div>

				<div class="drop col-3">
					<div class="dropdown">
						<input placeholder="Nhập nơi đến ..." class="form-control"></input>
						<div class="dropdown__list">
							<a href="#" class="dropdown__item">Hà Nội</a> <a href="#"
								class="dropdown__item">Quảng Ning</a> <a href="#"
								class="dropdown__item">Sài Gòn</a> <a href="#"
								class="dropdown__item">Đà Nẵng></a>
						</div>
					</div>
				</div>

				<div class=" drop col-3">
					<input class="form-control" type="date">
				</div>

				<div class="drop col-3">
					<button class="btn btn-danger">Tìm chuyến</button>
				</div>
			</div>
	</section>


  {% include 'customers/footer.html' %}
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
		crossorigin="anonymous"></script>
	<script
		src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
		crossorigin="anonymous"></script>
	<!-- owlCousel -->
	<script src="assets/lib/owl.carousel.min.js"></script>


	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
		integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
		crossorigin="anonymous"></script>
</body>

</html>

customers/templates/customers/login/login_view_notify.html
<!-- header -->
{% load static %}
<style>
  #errorNumberPhone {
    color: red;
  }
</style>
</head>
<header class="container-fluid myNavBar">
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="col-md-8 col-xl-7 col-lg-9 col-sm-6 d-flex">
      <a class="navbar-brand" href="/">
        <img src="{% static 'customers/images/logo1.png' %}" alt="logo" />
      </a>
      <div class="input-search">
        <form action="abc.com">
          <div class="input-group">
            <input
              type="text"
              class="form-control"
              placeholder="Search for anything"
            />
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fa fa-search"></i>
              </span>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-4 col-xl-5 col-lg-3 col-sm-4">
      <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav">
          <li class="nav-item business">
            <a class="nav-link" href="#">Thuê xe</a>
          </li>
          <li class="nav-item teach">
            <a class="nav-link" href="#">Quản lý Chuyến đi</a>
          </li>
        </ul>
      </div>
    </div>

    <button
      class="navbar-toggler d-lg-none col-sm-2"
      type="button"
      data-toggle="collapse"
      data-target="#collapsibleNavId"
      aria-controls="collapsibleNavId"
      aria-expanded="false"
      aria-label="Toggle navigation "
    >
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</header>
<!-- đăng nhập -->
<section class="dangnhap">
  <div
    class="modal"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    style="display: block !important; overflow-x: hidden; overflow-y: auto"
  >
    <div class="modal-dialog modal-dialog-centered modal-xl">
      <div class="modal-content login">
        <div class="modal-bodys">
          <div class="container">
            <div class="log__content">
              <div class="left">
                <div class="logo">
                  <img src="{% static 'customers/images/logo1.png' %}" alt="" />
                </div>

                <div class="log">
                  <img
                    alt=""
                    src="{% static 'customers/images/buy_ticket_login.jpg' %}"
                    style="width: 300px; height: 300px"
                  />
                </div>
              </div>

              <div class="right">
                <div
                  class=""
                  style="
                    display: flex;
                    justify-content: flex-end;
                    margin: -25px 15px 0 0;
                    height: auto;
                  "
                >
                  <a class="" href="/">
                    <button
                      type="button"
                      class="btn btn-outline-danger btn-sm btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    >
                      X
                    </button>
                  </a>
                </div>
                <h2>Login to your account</h2>
                <div class="mb-2" role="alert">
                  <div style="color: red"></div>
                </div>

                <form action="{% url 'customers:check' %}" method="POST">
                  {% csrf_token %} 
                  {% block messages %}
                  {% if messages %}
                    <ul class="messagelist">
                      <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="list-style:none; color: red">{{ messages }}</li>
                    </ul>
                  {% endif %}
                {% endblock messages %}
                  <div class="form-group">
                    <input
                      type="tel"
                      class="form-control top"
                      id="input"
                      aria-describedby="phoneHelp"
                      placeholder="Phone number"
                      name="numberPhone"
                      value=""
                      required
                      pattern="[0-9]{10}"
                    />
                    <div>
                      <p id="error"></p>
                    </div>
                  </div>

                  <div class="form-group">
                    <input
                      type="password"
                      class="form-control top"
                      id="password"
                      placeholder="Password"
                      required
                      name="password"
                      value=""
                    />
                    <div>
                      <p id="error2"></p>
                    </div>
                  </div>

                  <div class="form-group content">
                    <button type="button" class="btn  btn--white " data-toggle="modal" data-target="#modalForgot">
                      Forgot password
                    </button>
                  </div>
                  <button class="button3" type="submit">Login</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-backdrop show"></div>
</section>


<section class="forgotPassword">
  <div class="modal fade" id="modalForgot" tabindex="-1"
  aria-labelledby="modalForgot" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-xl">
    <div class="modal-content  forgot">
      <div class="modal-bodys">
        <div class="container ">
          <div class="log__content">
            <div class="left" style="
            margin-right: 35px;">
              <div class="logo">
                <img src="{% static 'customers/images/logo1.png' %}" alt="">
              </div>
              <div class="log">
                <img alt="" src="{% static 'customers/images/buy_ticket_login.jpg' %}"
                  style="width: 300px; height: 300px;">
              </div>
            </div>
            <div class="right">
              <div class=""
                style="display: flex; justify-content: flex-end; margin: -25px 15px 0 0; height: auto">
                <a class="" href="/">
                  <button type="button"
                    class="btn btn-outline-danger btn-sm btn-close"
                    data-bs-dismiss="modal" aria-label="Close">X</button>
                </a>
              </div>
              <H2>Forgot password</H2>
              <form action="/forgotPassword" method="POST">
                {% csrf_token %} 
                {% if messages %}
                 {% comment %} {{messages}} {% endcomment %}
                {% endif %}
                <div class="form-group">
                  <input
                    type="tel"
                    class="form-control top"
                    id="_phoneNumber"
                    aria-describedby="phoneHelp"
                    placeholder="Phone number"
                    name="numberPhoneForgotPassword"
                    value=""
                    pattern="[0-9]{10}"
                    required
                  />
              
                   <p id="errorNumberPhone" style="
                   display: flex;"
                   ></p>
                </div>
                <div class="" style="
                display: flex;
                justify-content: space-between;">
                  <button class="button3" style="
                  margin: 0;
                  margin-right: auto;
                  width: 23%;
                  margin-left: 0px;
              "
              type="submit">Submit</button>
                </div>
               
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

<script type="text/javascript">
function validatePhoneNumber(input_str) {
  var re = /^\(?(\d{3})\)?[- ]?(\d{3})[- ]?(\d{4})$/;

  return re.test(input_str);
}

var _phoneNumber = document.getElementById("_phoneNumber");
_phoneNumber.onblur = function () {
  if (!validatePhoneNumber(_phoneNumber.value)) {
    _phoneNumber.classList.add("invalid");
    errorNumberPhone.innerHTML = "Please enter a correct number phone.";
  }
};

_phoneNumber.onfocus = function () {
  if (this.classList.contains("invalid")) {
    this.classList.remove("invalid");
    errorNumberPhone.innerHTML = "";
  }
};


</script>

<script type="text/javascript">
  function validatePhoneNumber(input_str) {
    var re = /^\(?(\d{3})\)?[- ]?(\d{3})[- ]?(\d{4})$/;

    return re.test(input_str);
  }

  var input = document.getElementById("input");
  var password = document.getElementById("password");
  input.onblur = function () {
    if (!validatePhoneNumber(input.value)) {
      input.classList.add("invalid");
      error2.innerHTML = "Please enter a correct number phone.";
    }
  };

  input.onfocus = function () {
    if (this.classList.contains("invalid")) {
      this.classList.remove("invalid");
      error2.innerHTML = "";
    }
  };

  password.onblur = function () {
    if (password.value.length === 0) {
      password.classList.add("invalid");
      error2.innerHTML = "Please enter a correct password.";
    }
  };

  password.onfocus = function () {
    if (this.classList.contains("invalid")) {
      this.classList.remove("invalid");
      error2.innerHTML = "";
    }
  };
</script>